services:
  backend:
    build: ./mern/backend
    container_name: backend_container
    ports:
      - "5050:5050" 
    networks:
      - mern_network
    volumes:
      - backend_volume:/app
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase  
    depends_on:
      - mongodb

  frontend:
    build: ./mern/frontend
    container_name: front_container
    ports:
      - "5173:5173"  
    networks:
      - mern_network
    depends_on:
      - backend
    volumes:
      - frontend_volume:/app
  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db 

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mern_network
    depends_on:
       - nginx

  nginx:
    build:
      context: ./nginx
    container_name: nginx_container
    ports:
      - "80:80" 
    networks:
      - mern_network
    volumes:
      - ./nginx_log:/var/log/nginx
    depends_on:
      - backend
  
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter_container
    ports:
      - "9113:9113"
    networks:
      - mern_network
    depends_on:
      - prometheus
    command:
      - --nginx.scrape-uri=http://nginx:80/nginx_status
    environment:
      NGINX_HOST: "nginx" 
      NGINX_PORT: "80"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    networks:
      - mern_network
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "Ankit@123"    

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch_container
    environment: 
      - discovery.type= single-node
      - ES_JAVA_OPTS=-Xmx1g -Xms1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - mern_network
    depends_on:
      - nginx

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana_container
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - mern_network
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.0
    container_name: filebeat_container
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx_log:/usr/share/filebeat/logs
    networks:
      - mern_network
    depends_on:
      - elasticsearch
      - kibana

networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local
  backend_volume:
    driver: local  
  frontend_volume:
    driver: local
  elasticsearch_data:
    driver: local
  nginx_log:
    driver: local


